apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sleegg-com-tls
spec:
  secretName: sleegg-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sleegg.com
  dnsNames:
    - sleegg.com
    - www.sleegg.com
